# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem 'faker', '~> 2.21'
# gem 'byebug', '~> 11.1', '>= 11.1.3'
# gem 'rspec', '~> 3.11'
# gem 'ruby2d', '~> 0.9.5'

gem 'ruby2d', '~> 0.11.3'